renamed random, pipe to stderr

diff --git a/scripts/certified.in b/scripts/certified.in
--- a/scripts/certified.in
+++ b/scripts/certified.in
@@ -3,7 +3,7 @@ build=$(dirname "${BASH_SOURCE[0]}")
 check="$build/check"
 aigsim="$build/aiger/aigsim"
 for i in check aigsim; do
-    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" && exit 1
+    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
 done
 "$check" >/dev/null || exit 1
 [ $# -lt 2 ] && echo "usage: $(basename $0) <model checker> <model> [--mc_time=<limit>] [<model checker args>]" && exit 0
@@ -27,7 +27,10 @@ case $res in
         echo $(basename $0): model checker timeout
         exit 0
         ;;
-    0) exit 1 ;;
+    0)
+        echo $(basename $0): Error: model checker exit code needs to signal SAFE/UNSAFE
+        exit 1
+        ;;
     10)
         "$aigsim" -w -m "$MODEL" "$WIT" | grep -q 'Trace is a witness for: { b0 }' &&
             echo $(basename $0): produced valid trace
diff --git a/scripts/certifuzzer.in b/scripts/certifuzzer.in
--- a/scripts/certifuzzer.in
+++ b/scripts/certifuzzer.in
@@ -2,9 +2,10 @@
 build=$(dirname "${BASH_SOURCE[0]}")
 BUGS="$build/bug"
 fuzz="$build/fuzz"
+certified="$build/certified"
 status="$build/status"
-for i in fuzz status; do
-  [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" && exit 1
+for i in fuzz certified status; do
+  [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
 done
 "$fuzz" >/dev/null || exit 1
 [ $# -lt 1 ] && echo "usage: $(basename $0) <model checker> [<cores>=8]" && exit 0
@@ -13,10 +14,11 @@ cleanup() {
   jobs -rp | xargs -r kill
   wait
   if ls "$BUGS"/aag-*.aag >/dev/null 2>&1; then
-    echo -e "\n$(basename $0): $(basename $MC) on shortes bug"
+    echo -e "\n$(basename $0): $(basename $MC) on shortes bug\n"
     short=$(wc -l "$BUGS"/aag-*.aag | sort -n | head -n 1 | awk '{print $2}')
     cp "$short" "$build"/bug.aag
     "$MC" "$build"/bug.aag "$build"/wit.aag
+    "$certified" "$MC" "$build"/bug.aag
     echo
     echo $(basename $0): "Found a bug of length" $(wc -l "$build"/bug.aag | awk '{print $1}'): $(head -n 1 "$build"/bug.aag)
     echo $(basename $0): "with witness of length" $(wc -l "$build"/wit.aag | awk '{print $1}')
diff --git a/scripts/check.in b/scripts/check.in
--- a/scripts/check.in
+++ b/scripts/check.in
@@ -7,7 +7,7 @@ aigtocnf="$build/aiger/aigtocnf"
 qaiger2qcir="$build/quabs/qaiger2qcir"
 quabs="$build/quabs/quabs"
 for i in certifaiger sat_solver aigtocnf; do
-    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" && exit 1
+    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
 done
 [ $# -lt 2 ] && echo "usage: $(basename $0) <model> <witness>" && exit 0
 mkdir -p ${TMPDIR:-/tmp}/froleyks-certifaiger
@@ -34,7 +34,7 @@ echo
 ALL_SUCCESS=true
 if [ $qbf = true ]; then
     for i in qaiger2qcir quabs; do
-        [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" && exit 1
+        [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
     done
     echo Checking reset with quantification
     check="${CHECKS[0]}"
diff --git a/scripts/fuzz.in b/scripts/fuzz.in
--- a/scripts/fuzz.in
+++ b/scripts/fuzz.in
@@ -2,11 +2,11 @@
 FAILURES=1 # number of failures before exit
 build=$(dirname "${BASH_SOURCE[0]}")
 BUGS="$build/bug"
-test="$build/test"
-for i in test; do
-    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" && exit 1
+random="$build/random"
+for i in random; do
+    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
 done
-"$test" >/dev/null || exit 1
+"$random" >/dev/null || exit 1
 [ $# -lt 1 ] && echo "usage: $(basename $0) <model checker>" && exit 0
 MC=$(realpath $1)
 mkdir -p ${TMPDIR:-/tmp}/froleyks-certifaiger
@@ -22,7 +22,7 @@ unsafe=0
 timeout=0
 failed=0
 while true; do
-    "$test" "$MC" >"$out"
+    "$random" "$MC" >"$out"
     res=$?
     if [ $res -eq 0 ]; then
         if grep -q 'certified: produced valid witness circuit' "$out"; then
