constraint branch cherry pick

diff --git a/scripts/certified.in b/scripts/certified.in
--- a/scripts/certified.in
+++ b/scripts/certified.in
@@ -1,48 +1,51 @@
 #!/usr/bin/env bash
-build=$(dirname "${BASH_SOURCE[0]}")
+build=$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
 check="$build/check"
 simulate="$build/simulate"
 for i in check simulate; do
-    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
+    [ ! -x "${!i}" ] && echo "$(basename "$0"): missing executable $i (${!i})" >&2 && exit 1
 done
 "$check" >/dev/null || exit 1
 "$simulate" >/dev/null || exit 1
-[ $# -lt 2 ] && echo "usage: $(basename $0) <model checker> <model> [--mc_time=<limit>] [<model checker args>]" && exit 0
+[ $# -lt 2 ] && echo "usage: $(basename "$0") <model checker> <model> [--mc_time=<limit>] [<model checker args>]" && exit 0
 mkdir -p ${TMPDIR:-/tmp}/froleyks-certifaiger
-TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename $0)-XXXXXXXX)
+TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename "$0")-XXXXXXXX)
 trap 'rm -rf "${TMP}"; exit' EXIT HUP INT QUIT TERM
-MC=$(realpath $1)
-MODEL=$(realpath $2)
-echo $(basename $0): running "$MC" on "$MODEL"
-WIT=$TMP/wit_$(basename $MODEL)
-SIM=$TMP/sim_$(basename $MODEL)
-shift 2
 if [[ $1 =~ --mc_time=([0-9]+) ]]; then
     limit="timeout ${BASH_REMATCH[1]} "
+    shift 1
+fi
+MC="$1"
+MODEL=$(realpath $2)
+echo $(basename "$0"): running "$MC" on "$MODEL"
+WIT=$TMP/wit_$(basename $MODEL)
+if [[ $# -ge 3 && $3 != -* ]]; then
+    WIT="$3"
+    echo $(basename "$0"): writing "$WIT"
     shift
 fi
-
-$limit "$MC" "$MODEL" "$WIT" "$@"
+shift 2
+$limit $MC "$MODEL" "$WIT" "$@"
 res=$?
-echo $(basename $0): model checker exit code $res
+echo $(basename "$0"): model checker exit code $res
 case $res in
-    124)
-        echo $(basename $0): model checker timeout
-        exit 0
-        ;;
-    0)
-        echo $(basename $0): Error: model checker exit code needs to signal SAFE/UNSAFE
-        exit 1
-        ;;
-    10)
-        "$simulate" "$MODEL" "$WIT"
-        res=$?
-        [ $res -eq 0 ] && echo $(basename $0): produced valid trace
-        ;;
-    20)
-        "$check" "$MODEL" "$WIT"
-        res=$?
-        [ $res -eq 0 ] && echo $(basename $0): produced valid witness circuit
-        ;;
+124)
+    echo $(basename "$0"): model checker timeout
+    exit 0
+    ;;
+0)
+    echo $(basename "$0"): Error: model checker exit code needs to signal SAFE/UNSAFE
+    exit 1
+    ;;
+10)
+    "$simulate" "$MODEL" "$WIT"
+    res=$?
+    [ $res -eq 0 ] && echo $(basename "$0"): produced valid trace
+    ;;
+20)
+    "$check" "$MODEL" "$WIT"
+    res=$?
+    [ $res -eq 0 ] && echo $(basename "$0"): produced valid witness circuit
+    ;;
 esac
 exit $res
diff --git a/scripts/certifuzzer.in b/scripts/certifuzzer.in
--- a/scripts/certifuzzer.in
+++ b/scripts/certifuzzer.in
@@ -1,29 +1,29 @@
 #!/usr/bin/env bash
-build=$(dirname "${BASH_SOURCE[0]}")
+build=$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
 BUGS="$build/bug"
 fuzz="$build/fuzz"
 certified="$build/certified"
 status="$build/status"
+options="$build/options"
 for i in fuzz certified status; do
-  [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
+  [ ! -x "${!i}" ] && echo "$(basename "$0"): missing executable $i (${!i})" >&2 && exit 1
 done
 "$fuzz" >/dev/null || exit 1
-[ $# -lt 1 ] && echo "usage: $(basename $0) <model checker> [<cores>=8]" && exit 0
+[ $# -lt 1 ] && echo "usage: $(basename "$0") <model checker> [<cores>=8]" && exit 0
 cleanup() {
   echo
   jobs -rp | xargs -r kill
   wait
   if ls "$BUGS"/aag-*.aag >/dev/null 2>&1; then
-    echo -e "\n$(basename $0): $(basename $MC) on shortes bug\n"
+    echo -e "\n$(basename "$0"): $(basename $MC) on shortes bug\n"
     short=$(wc -l "$BUGS"/aag-*.aag | sort -n | head -n 1 | awk '{print $2}')
     cp "$short" "$build"/bug.aag
-    "$MC" "$build"/bug.aag "$build"/wit.aag
-    "$certified" "$MC" "$build"/bug.aag
+    "$certified" "$MC" "$build"/bug.aag "$build"/wit.aag
     echo
-    echo $(basename $0): "Found a bug of length" $(wc -l "$build"/bug.aag | awk '{print $1}'): $(head -n 1 "$build"/bug.aag)
-    echo $(basename $0): "with witness of length" $(wc -l "$build"/wit.aag | awk '{print $1}')
-    echo $(basename $0): "$build"/bug.aag
-    echo $(basename $0): "$build"/wit.aag
+    echo $(basename "$0"): "Found a bug of length" $(wc -l "$build"/bug.aag | awk '{print $1}'): $(head -n 1 "$build"/bug.aag)
+    echo $(basename "$0"): "with witness of length" $(wc -l "$build"/wit.aag | awk '{print $1}')
+    echo $(basename "$0"): "$build"/bug.aag
+    echo $(basename "$0"): "$build"/wit.aag
   fi
   trap '' EXIT HUP INT QUIT TERM
   exit
@@ -31,18 +31,18 @@ cleanup() {
 trap 'cleanup' EXIT HUP INT QUIT TERM
 MC=$(realpath $1)
 n=${2:-8}
-echo $(basename $0): fuzzing $(basename "$MC") with $n thredas
+echo $(basename "$0"): fuzzing $(basename "$MC") with $n thredas
 old_bugs=$(ls "$BUGS"/aag-*.aag 2>/dev/null | wc -l)
 if [ $old_bugs -gt 0 ]; then
-  echo $(basename $0): "Warning: $old_bugs failure inducing inputs from previous runs found"
-  echo $(basename $0): "run rm -r $BUGS"
+  echo $(basename "$0"): "Warning: $old_bugs failure inducing inputs from previous runs found"
+  echo $(basename "$0"): "run rm -r $BUGS"
 fi
 echo
-"$MC" --range >options
+"$MC" --range >"$options"
 sed -i \
   -e '/verbosity/d' \
   -e '/certificate/d' \
-  options
+  "$options"
 i=0
 while [ $i -lt "$n" ]; do
   "$fuzz" "$MC" --time=60 &
diff --git a/scripts/check.in b/scripts/check.in
--- a/scripts/check.in
+++ b/scripts/check.in
@@ -1,5 +1,5 @@
 #!/usr/bin/env bash
-build=$(dirname "${BASH_SOURCE[0]}")
+build=$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
 certifaiger="$build/certifaiger"
 sat_solver="$build/kissat/kissat"
 aigtocnf="$build/aiger/aigtocnf"
@@ -7,38 +7,35 @@ aigtocnf="$build/aiger/aigtocnf"
 qaiger2qcir="$build/quabs/qaiger2qcir"
 quabs="$build/quabs/quabs"
 for i in certifaiger sat_solver aigtocnf; do
-    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
+    [ ! -x "${!i}" ] && echo "$(basename "$0"): missing executable $i (${!i})" >&2 && exit 1
 done
-[ $# -lt 2 ] && echo "usage: $(basename $0) <model> <witness>" && exit 0
+[ $# -lt 2 ] && echo "usage: $(basename "$0") <model> <witness>" && exit 0
 mkdir -p ${TMPDIR:-/tmp}/froleyks-certifaiger
-TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename $0)-XXXXXXXX)
+TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename "$0")-XXXXXXXX)
 trap 'rm -rf ${TMP}; exit' EXIT HUP INT QUIT TERM
 CHECKS=(reset constraint transition property base step)
 AIGS=()
 for check in "${CHECKS[@]}"; do
     AIGS+=("${TMP}/$check.aig")
 done
-qbf=false
-echo $(basename $0): Checking witness circuit "$2"
+non_stratified=false
+echo $(basename "$0"): Checking witness circuit "$2"
 $certifaiger "$1" "$2" "${AIGS[@]}"
 certifaiger_exit=$?
-if [ $certifaiger_exit -ne 0 ]; then
-    if [ $certifaiger_exit -eq 15 ]; then
-        qbf=true
-    else
-        echo "$(basename $0): Error: certifaiger failed with exit code $certifaiger_exit"
-        exit 1
-    fi
-fi
+case $certifaiger_exit in
+0) ;;
+15)
+    non_stratified=true
+    CHECKS=(constraint transition property base step)
+    ;;
+*) echo "Error: certifaiger failed with exit code $certifaiger_exit" ;;
+esac
 echo
 
 ALL_SUCCESS=true
-if [ $qbf = true ]; then
-    for i in qaiger2qcir quabs; do
-        [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
-    done
-    echo Checking reset with quantification
-    check="${CHECKS[0]}"
+if [ $non_stratified = true ]; then
+    check="reset"
+    echo Checking ${check} with quantification
     $qaiger2qcir "${TMP}/$check.aig" >"${TMP}/$check.qcir"
     $quabs "${TMP}/$check.qcir"
     if [ $? -ne 20 ]; then
@@ -46,7 +43,6 @@ if [ $qbf = true ]; then
         echo "Error: ${check} check failed"
     fi
     echo
-    CHECKS=("${CHECKS[@]:1}")
 fi
 for check in "${CHECKS[@]}"; do
     echo Checking "$check"
diff --git a/scripts/fuzz.in b/scripts/fuzz.in
--- a/scripts/fuzz.in
+++ b/scripts/fuzz.in
@@ -1,21 +1,21 @@
 #!/usr/bin/env bash
 FAILURES=1 # number of failures before exit
-build=$(dirname "${BASH_SOURCE[0]}")
+build=$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
 BUGS="$build/bug"
 random="$build/random"
 for i in random; do
-    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
+    [ ! -x "${!i}" ] && echo "$(basename "$0"): missing executable $i (${!i})" >&2 && exit 1
 done
 "$random" >/dev/null || exit 1
-[ $# -lt 1 ] && echo "usage: $(basename $0) <model checker>" && exit 0
+[ $# -lt 1 ] && echo "usage: $(basename "$0") <model checker>" && exit 0
 MC=$(realpath $1)
 mkdir -p ${TMPDIR:-/tmp}/froleyks-certifaiger
-TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename $0)-XXXXXXXX)
+TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename "$0")-XXXXXXXX)
 trap 'rm -rf ${TMP}; exit' EXIT HUP INT QUIT TERM
 
 log="$TMP/log"
 out="$TMP/out"
-# echo $(basename $0) logging to "$log"
+# echo $(basename "$0") logging to "$log"
 i=0
 safe=0
 unsafe=0
@@ -32,7 +32,7 @@ while true; do
         elif grep -q 'certified: model checker timeout' "$out"; then
             ((timeout += 1))
         else
-            echo "$(basename $0): ERROR in certified"
+            echo "$(basename "$0"): ERROR in certified"
             exit 1
         fi
         (((i += 1) % 10)) || echo fuzzed: $i $safe $unsafe $timeout $failed >>"$log"
diff --git a/scripts/random.in b/scripts/random.in
--- a/scripts/random.in
+++ b/scripts/random.in
@@ -1,30 +1,32 @@
 #!/usr/bin/env bash
 FUZZER_OPTIONS='-2 -m -S -s'
-build=$(dirname "${BASH_SOURCE[0]}")
+# FUZZER_OPTIONS='-2 -m -S'
+build=$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
 BUGS="$build/bug"
 certified="$build/certified"
 aigfuzz="$build/aiger/aigfuzz"
 aigdd="$build/aiger/aigdd"
 aigtoaig="$build/aiger/aigtoaig"
+options="$build/options"
 for i in certified aigfuzz aigdd aigtoaig; do
-    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
+    [ ! -x "${!i}" ] && echo "$(basename "$0"): missing executable $i (${!i})" >&2 && exit 1
 done
 "$certified" >/dev/null || exit 1
-[ $# -lt 1 ] && echo "usage: $(basename $0) <model checker> [<seed>]" && exit 0
+[ $# -lt 1 ] && echo "usage: $(basename "$0") <model checker> [<seed>]" && exit 0
 MC=$(realpath $1)
 [ $# -gt 1 ] && seed=$2
-[ -f "$build/option" ] && FUZZER_OPTIONS="$FUZZER_OPTIONS -r $build/option"
+[ -f "$options" ] && FUZZER_OPTIONS="$FUZZER_OPTIONS -r $options"
 mkdir -p ${TMPDIR:-/tmp}/froleyks-certifaiger
-TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename $0)-XXXXXXXX)
+TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename "$0")-XXXXXXXX)
 trap 'rm -rf ${TMP}; exit' EXIT HUP INT QUIT TERM
 
 mod="$TMP/mod.aig"
 rm -f "$mod"
 "$aigfuzz" $FUZZER_OPTIONS $seed >"$mod"
 [ -z $seed ] && seed=$(grep -a 'seed' "$mod" | head -1 | awk '{print $NF}')
-echo $(basename $0): seed $seed
-echo $(basename $0): $(head -n 1 "$mod")
-"$certified" "$MC" "$mod" && exit 0
+echo $(basename "$0"): seed $seed
+echo $(basename "$0"): $(head -n 1 "$mod")
+"$certified" --mc_time=60 "$MC" "$mod" && exit 0
 res=$?
 echo bug: $seed
 mkdir -p "$BUGS"
@@ -34,5 +36,5 @@ aag="$BUGS"/aag-$seed.aag
 mv "$mod" "$big"
 "$aigdd" $big $red "$certified $MC"
 "$aigtoaig" $red $aag
-echo $(basename $0): reduced $(head -n 1 "$aag") "$(realpath $aag)"
+echo $(basename "$0"): reduced $(head -n 1 "$aag") "$(realpath $aag)"
 exit $res
diff --git a/scripts/simulate.in b/scripts/simulate.in
--- a/scripts/simulate.in
+++ b/scripts/simulate.in
@@ -1,12 +1,12 @@
 #!/usr/bin/env bash
-build=$(dirname "${BASH_SOURCE[0]}")
+build=$(cd -- "$(dirname "${BASH_SOURCE[0]}")" && pwd -P)
 aigsim="$build/aiger/aigsim"
 for i in aigsim; do
-    [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
+    [ ! -x "${!i}" ] && echo "$(basename "$0"): missing executable $i (${!i})" >&2 && exit 1
 done
-[ $# -lt 2 ] && echo "usage: $(basename $0) <model> <trace>" && exit 0
+[ $# -lt 2 ] && echo "usage: $(basename "$0") <model> <trace>" && exit 0
 mkdir -p ${TMPDIR:-/tmp}/froleyks-certifaiger
-TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename $0)-XXXXXXXX)
+TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename "$0")-XXXXXXXX)
 trap 'rm -rf "${TMP}"; exit' EXIT HUP INT QUIT TERM
 SIM=$TMP/sim_$(basename $1)
 head=$(head -n 1 $1)
@@ -14,13 +14,13 @@ head=($head)
 head+=(0 0 0 0)
 ((${head[6]} == 0)) && MOVE_OUTPUT="-m"
 
-echo $(basename $0): simulating trace "$2"
+echo $(basename "$0"): simulating trace "$2"
 "$aigsim" $MOVE_OUTPUT -w "$1" "$2" >"$SIM"
 if grep -q 'Trace is a witness for: { b0' "$SIM"; then
-    echo $(basename $0): produced valid trace
+    echo $(basename "$0"): produced valid trace
     exit 0
 else
-    echo $(basename $0): Error invalid trace
+    echo $(basename "$0"): Error invalid trace
     (($(wc -l <"$SIM") > 1)) && cat "$SIM"
     exit 1
 fi
