proof checking

diff --git a/scripts/check_unsat.in b/scripts/check_unsat.in
--- a/scripts/check_unsat.in
+++ b/scripts/check_unsat.in
@@ -1,7 +1,8 @@
 #!/usr/bin/env bash
 bin="$(cd -- "$(dirname "$(readlink -f "${BASH_SOURCE[0]}")")" && pwd -P)"
 certifaiger="$bin"/certifaiger
-sat_solver="$bin"/@SAT@
+sat_solver="$bin/@SAT@"
+[ -n "@SAT_CHECKER@" ] && sat_checker="$bin/@SAT_CHECKER@"
 aigtocnf="$bin"/aigtocnf
 aigsplit="$bin"/aigsplit
 for i in certifaiger sat_solver aigtocnf aigsplit; do
@@ -37,11 +38,23 @@ $aigsplit "$check".aig split_ || {
 sat() {
     echo Checking $1
     $aigtocnf "${TMP}/$2" "${TMP}/$2.cnf"
-    $sat_solver --unsat --quiet "${TMP}/$2.cnf"
+    [ -n "$sat_checker" ] && proof="${TMP}/$2.proof"
+    [ "$(basename "$sat_checker")" = "lrat-trim" ] && format=--lrat
+    $sat_solver --unsat --quiet $format "${TMP}/$2.cnf" $proof
     if [ $? -ne 20 ]; then
         echo "Error: $1 check failed"
         exit 1
     fi
+    if [ -n "$sat_checker" ]; then
+        expected=0
+        [ "$(basename "$sat_checker")" = "lrat-trim" ] && expected=20 && quiet=--quiet
+        $sat_checker $quiet "${TMP}/$2.cnf" $proof
+        if [ $? -ne $expected ]; then
+            echo "Error: $1 proof check failed"
+            exit 1
+        fi
+    fi
+    rm -f "$proof"
 }
 
 CHECKS=(reset transition property base step)
