parallel checks

diff --git a/scripts/check_unsat.in b/scripts/check_unsat.in
--- a/scripts/check_unsat.in
+++ b/scripts/check_unsat.in
@@ -10,7 +10,7 @@ done
 [ $# -lt 2 ] && echo "usage: $(basename "$0") <model> <witness>" && exit 0
 mkdir -p ${TMPDIR:-/tmp}/froleyks-certifaiger
 TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename "$0")-XXXXXXXX)
-# trap 'rm -rf ${TMP}; exit' EXIT HUP INT QUIT TERM
+trap 'rm -rf ${TMP}; exit' EXIT HUP INT QUIT TERM
 model="$1"
 witness="$2"
 check="${model##*/}"
@@ -29,11 +29,33 @@ $aigsplit "$check".aig split_ || {
     exit 1
 }
 
-for c in split_*; do
-    $aigtocnf "$c" "$c".cnf
-    $sat_solver --quiet "$c".cnf
+CHECKS=(reset transition property base step)
+PIDS=()
+for i in {0..4}; do
+    aig="split_o$i"
+    name="${CHECKS[i]}"
+    echo "Checking $name"
+    if [ "$SEQUENTIAL" -eq 1 ]; then
+        $sat_solver --quiet "${TMP}/${aig}.cnf"
+        if [ $? -ne 20 ]; then
+            echo "Error: ${name} check failed"
+            echo $(basename "$0"): Certificate check failed.
+            exit 1
+        fi
+    else
+        (
+            $sat_solver --quiet "${TMP}/$1.cnf"
+            if [ $? -ne 0 ]; then
+                echo "Error: $1 check failed"
+                exit 1
+            fi
+        ) &
+        PIDS+=($!)
+    fi
+done
+for pid in "${PIDS[@]}"; do
+    wait "$pid"
     if [ $? -ne 20 ]; then
-        echo "Error: $c failed"
         echo $(basename "$0"): Certificate check failed.
         exit 1
     fi
