embedded constraint checks

diff --git a/scripts/check.in b/scripts/check.in
--- a/scripts/check.in
+++ b/scripts/check.in
@@ -13,32 +13,56 @@ done
 mkdir -p ${TMPDIR:-/tmp}/froleyks-certifaiger
 TMP=$(mktemp -d "${TMPDIR:-/tmp}"/froleyks-certifaiger/$(basename $0)-XXXXXXXX)
 trap 'rm -rf ${TMP}; exit' EXIT HUP INT QUIT TERM
-CHECKS=(reset constraint transition property base step)
+CHECKS=(reset transition property base step)
 AIGS=()
 for check in "${CHECKS[@]}"; do
     AIGS+=("${TMP}/$check.aig")
 done
-qbf=false
 echo $(basename $0): Checking witness circuit "$2"
 $certifaiger "$1" "$2" "${AIGS[@]}"
 certifaiger_exit=$?
-if [ $certifaiger_exit -ne 0 ]; then
-    if [ $certifaiger_exit -eq 15 ]; then
-        qbf=true
-    else
-        echo "$(basename $0): Error: certifaiger failed with exit code $certifaiger_exit"
-        exit 1
-    fi
-fi
+non_stratified=false
+non_shared_constraint=false
+case $certifaiger_exit in
+    0) ;;
+    1)
+        non_stratified=true
+        CHECKS=(transition property base step)
+        ;;
+    2)
+        non_shared_constraint=true
+        CHECKS=(reset property base step)
+        ;;
+    3)
+        non_stratified=true
+        non_shared_constraint=true
+        CHECKS=(property base step)
+        ;;
+    *) echo "Error: certifaiger failed with exit code $certifaiger_exit" ;;
+esac
 echo
 
 ALL_SUCCESS=true
-if [ $qbf = true ]; then
+if [ $non_stratified = true ] || [ $non_shared_constraint = true ]; then
     for i in qaiger2qcir quabs; do
         [ ! -x "${!i}" ] && echo "$(basename $0): missing executable $i (${!i})" >&2 && exit 1
     done
-    echo Checking reset with quantification
-    check="${CHECKS[0]}"
+fi
+if [ $non_stratified = true ]; then
+    check="reset"
+    echo Checking ${check} with quantification
+    $qaiger2qcir "${TMP}/$check.aig" >"${TMP}/$check.qcir"
+    $quabs "${TMP}/$check.qcir"
+    if [ $? -ne 20 ]; then
+        ALL_SUCCESS=false
+        echo "Error: ${check} check failed"
+    fi
+    echo
+    CHECKS=("${CHECKS[@]:1}")
+fi
+if [ $non_stratified = true ]; then
+    check="transition"
+    echo Checking ${check} with quantification
     $qaiger2qcir "${TMP}/$check.aig" >"${TMP}/$check.qcir"
     $quabs "${TMP}/$check.qcir"
     if [ $? -ne 20 ]; then
